disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  - force_cast
  - force_try
#  - empty_count
  - cyclomatic_complexity
  - large_tuple
  - for_where
  - multiple_closures_with_trailing_closure
  - redundant_string_enum_value
  - implicit_getter
  - function_parameter_count
  - unused_enumerated
  - vertical_parameter_alignment
  - identifier_name
  - line_length
opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - newmoneybook/UIObject/Charts
    - Pods
    - newmoneybookTests
    - newmoneybookUITests
    - "*.m"
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

function_body_length:
  warning: 200
  error: 300
type_body_length:
  - 500 # warning
  - 600 # error
file_length:
  warning: 2000
  error: 2500
nesting:
  type_level: 3

type_name:
  min_length: 1 # only warning
  max_length: # warning and error
    warning: 100
    error: 150
  allowed_symbols: ["_"] # these are allowed in type names
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
